#!/bin/bash

ds=*/
if [[ $1 ]]; then ds=$1; fi

for d in $ds; do
  dir=$(basename $d)
  docker build -t caub/$dir:latest $dir -f $dir/Dockerfile
  docker push caub/$dir
done

if [[ ! $1 || $1 == 'node' ]]; then
  dockerfile=$(curl -s https://raw.githubusercontent.com/nodejs/docker-node/master/11/stretch-slim/Dockerfile | sed -e '/RUN groupadd/,+2d' | sed -e '/ENV YARN/,$d')
  docker build -t caub/node . -f -<<EOF
$dockerfile
RUN useradd node && mkdir -p /home/node && chown -R node:node /home/node
CMD ["node"]
EOF
  docker push caub/node
fi

# todo run it in .travis.yml
